# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - name: checkout repo content
         uses: actions/checkout@v2 # checkout the repository content to github runner.
       - name: setup python
         uses: actions/setup-python@v2
         with:
           python-version: 3.8 #install the python needed
       - name: execute py script # run the run.py to get the latest data
         working-directory: ./data
         run: |
           python run.py
       - name: Commit files
         id: commit
         run: |
            git config --local user.email "action@github.com"
            git config --local user.name "github-actions"
            git add --all
            if [-z "$(git status --porcelain)"]; then
                echo "::set-output name=push::false"
            else
                git commit -m "Add changes" -a
                echo "::set-output name=push::true"
            fi
        shell: bash