# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var fs = require("fs");
            console.log("Going to write into existing file");
            // Open a new file with name input.txt and write Simply Easy Learning! to it.
            fs.writeFile('videos.json', 'Simply Easy Learning!', function(err) {
               if (err) {
                  return console.error(err);
               }
               console.log("Data written successfully!");
               console.log("Let's read newly written data");
            });